name: Test

on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main

concurrency:
  group: Test
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10","3.11","3.12" ]
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up python and poetry
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run pytest